# Generated by Django 5.0.9 on 2024-10-11 03:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Oder",
            new_name="Order",
        ),
        migrations.RenameModel(
            old_name="OderItem",
            new_name="OrderItem",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="date_oder",
            new_name="date_order",
        ),
        migrations.RenameField(
            model_name="orderitem",
            old_name="oder",
            new_name="order",
        ),
        migrations.RenameField(
            model_name="shippingaddress",
            old_name="cyti",
            new_name="city",
        ),
        migrations.RenameField(
            model_name="shippingaddress",
            old_name="oder",
            new_name="order",
        ),
    ]
