# Generated by Django 5.0.9 on 2024-10-12 17:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0008_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ManyToManyField(related_name="product", to="app.category"),
        ),
    ]
