# Generated by Django 5.0.9 on 2024-10-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0011_remove_product_category_alter_product_digital_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shippingaddress",
            name="city",
        ),
        migrations.RemoveField(
            model_name="shippingaddress",
            name="country",
        ),
        migrations.RemoveField(
            model_name="shippingaddress",
            name="date_added",
        ),
        migrations.RemoveField(
            model_name="shippingaddress",
            name="email",
        ),
        migrations.RemoveField(
            model_name="shippingaddress",
            name="order",
        ),
        migrations.RemoveField(
            model_name="shippingaddress",
            name="state",
        ),
        migrations.RemoveField(
            model_name="shippingaddress",
            name="zipcode",
        ),
        migrations.AddField(
            model_name="shippingaddress",
            name="phone_number",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
