# Generated by Django 5.0.9 on 2024-10-14 06:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0012_remove_shippingaddress_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="address",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="shipping_address",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="shipping_phone_number",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="shippingaddress",
            name="first_name",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shippingaddress",
            name="last_name",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="account",
            name="phone_number",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="shippingaddress",
            name="name",
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
