# Generated by Django 5.0.9 on 2024-10-14 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0013_account_address_account_shipping_address_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shippingaddress",
            name="address",
        ),
        migrations.RemoveField(
            model_name="shippingaddress",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="shippingaddress",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="shippingaddress",
            name="id",
        ),
        migrations.RemoveField(
            model_name="shippingaddress",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="shippingaddress",
            name="name",
        ),
        migrations.RemoveField(
            model_name="shippingaddress",
            name="phone_number",
        ),
        migrations.AddField(
            model_name="account",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="shippingaddress",
            name="account_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="app.account",
            ),
            preserve_default=False,
        ),
    ]
