# Generated by Django 5.0.9 on 2024-10-14 06:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0016_remove_account_customer_remove_shippingaddress_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="shipping_address",
        ),
        migrations.RemoveField(
            model_name="account",
            name="shipping_phone_number",
        ),
    ]
