# Generated by Django 5.0.9 on 2024-10-14 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0018_shippingaddress_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shippingaddress",
            name="account_ptr",
        ),
        migrations.AddField(
            model_name="account",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="shipping_address",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="shipping_phone_number",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="shippingaddress",
            name="address",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="shippingaddress",
            name="first_name",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shippingaddress",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=2,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shippingaddress",
            name="last_name",
            field=models.CharField(default=4, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shippingaddress",
            name="phone_number",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
